version: '3.9'

services:
  api:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: m-api
    volumes:
      - /app/node_modules

      - ./:/app
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    # environment:
    #   NODE_ENV: ${NODE_ENV}
    #   MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb
    # networks:
    #   - library-mern-api

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      # for persistence storage
      - mongodb-data:/data/db
    # networks:
    #   - library-mern-api
    container_name: m-mongodb

    # mongo-express should only be used privately for development purposes.
    # It helps us interact with a mongoDB database using our browser
  # mongo-express:
  #   image: mongo-express
  #   depends_on:
  #     - mongodb
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
  #     ME_CONFIG_MONGODB_SERVER: mongodb
  #     ME_CONFIG_BASICAUTH_USERNAME: admin
  #     ME_CONFIG_BASICAUTH_PASSWORD: admin123456
  #   volumes:
  #     - mongodb-data
  #   networks:
  #     - library-mern-api

  # client:
  #   restart: always
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile.dev
  #   container_name: library_mern_frontend
  #   volumes:
  #     - ./app/node_modules
  #     - ./client:/app
  #   # ports:
  #   #    - 3000:3000
  #   depends_on:
  #     - library-api
  #   networks:
  #     - library-mern-api

  client:
    restart: always
    # depends_on:
    #   - m-api
    build:
      context: ./client
      # dockerfile: ./client/Dockerfile
    ports:
      - 80:80
    # networks:
    #   - library-mern-api
    container_name: m-client

# networks:
#   library-mern-api:
#     driver: bridge

volumes:
  mongodb-data:
    driver: local
